### ISSUE TITLE
how to get performance analysis for this system

### ISSUE THREAD

**Issue by Savitha2018** [vshantam/ImageCaptioning#1]

**Comment by vshantam** [comment]
Well to calculate performance with linguistic data is very difficult because one sentence in a particular language can be represented in many different ways.

As of now, to the best of my knowledge, you can use **BLEU** score  which is called as **Bilingual** **Evaluation** to calculate the accuracy of caption generated.

Here are the reference links :- 
1. https://www.nltk.org/_modules/nltk/translate/bleu_score.html 
2. https://machinelearningmastery.com/calculate-bleu-score-for-text-python/
3. https://www.youtube.com/watch?v=DejHQYAGb7Q (**My Favourite**)
